"""create CountryBoundaries table

Revision ID: 7f7cec7df4de
Revises: c9ab45c37359
Create Date: 2025-05-08 16:02:42.455535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '7f7cec7df4de'
down_revision: Union[str, None] = 'c9ab45c37359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('natural_earth_country_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('country_iso3_id', sa.String(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_natural_earth_country_boundaries_geometry', 'natural_earth_country_boundaries', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_natural_earth_country_boundaries_country_iso3_id'), 'natural_earth_country_boundaries', ['country_iso3_id'], unique=False)
    op.create_index(op.f('ix_natural_earth_country_boundaries_country_name'), 'natural_earth_country_boundaries', ['country_name'], unique=False)
    op.create_index(op.f('ix_natural_earth_country_boundaries_id'), 'natural_earth_country_boundaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_natural_earth_country_boundaries_id'), table_name='natural_earth_country_boundaries')
    op.drop_index(op.f('ix_natural_earth_country_boundaries_country_name'), table_name='natural_earth_country_boundaries')
    op.drop_index(op.f('ix_natural_earth_country_boundaries_country_iso3_id'), table_name='natural_earth_country_boundaries')
    op.drop_geospatial_index('idx_natural_earth_country_boundaries_geometry', table_name='natural_earth_country_boundaries', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('natural_earth_country_boundaries')
    # ### end Alembic commands ###
