"""add country iso3 id in FAOCountryCropYield table

Revision ID: c9ab45c37359
Revises: f88f69337b2b
Create Date: 2025-05-08 15:35:40.052099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ab45c37359'
down_revision: Union[str, None] = 'f88f69337b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fao_country_crop_yield', sa.Column('country_iso3_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_fao_country_crop_yield_country_iso3_id'), 'fao_country_crop_yield', ['country_iso3_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fao_country_crop_yield_country_iso3_id'), table_name='fao_country_crop_yield')
    op.drop_column('fao_country_crop_yield', 'country_iso3_id')
    # ### end Alembic commands ###
