"""Create FAOCountryCropYield table

Revision ID: f88f69337b2b
Revises: 
Create Date: 2025-05-07 17:52:25.195193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88f69337b2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fao_country_crop_yield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('crop_name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value_source', sa.String(), nullable=True),
    sa.Column('area_harvested', sa.Float(), nullable=True),
    sa.Column('yield_kg_per_ha', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fao_country_crop_yield_country_name'), 'fao_country_crop_yield', ['country_name'], unique=False)
    op.create_index(op.f('ix_fao_country_crop_yield_crop_name'), 'fao_country_crop_yield', ['crop_name'], unique=False)
    op.create_index(op.f('ix_fao_country_crop_yield_id'), 'fao_country_crop_yield', ['id'], unique=False)
    op.create_index(op.f('ix_fao_country_crop_yield_year'), 'fao_country_crop_yield', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fao_country_crop_yield_year'), table_name='fao_country_crop_yield')
    op.drop_index(op.f('ix_fao_country_crop_yield_id'), table_name='fao_country_crop_yield')
    op.drop_index(op.f('ix_fao_country_crop_yield_crop_name'), table_name='fao_country_crop_yield')
    op.drop_index(op.f('ix_fao_country_crop_yield_country_name'), table_name='fao_country_crop_yield')
    op.drop_table('fao_country_crop_yield')
    # ### end Alembic commands ###
